---
############################
#  SHARED

cf: &cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((((env))-cf-username))
  CF_PASSWORD: ((((env))-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: ((env))

node-image: &node-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: node
      tag: 16.14

cf-image: &cf-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: 18fgsa/concourse-task

test: &test
  - in_parallel:
    - get: redis
      params: {save: true}
    - get: node
      params: {save: true}
  - task: prepare
    config:
      <<: *node-image
      inputs: [name: src]
      outputs: [name: src]
      run:
        dir: src
        path: bash
        args:
          - -c
          - |
            yarn --pure-lockfile
            yarn eslint
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: karlkfi/concourse-dcind
      inputs:
        - name: src
        - name: redis
        - name: node
      run:
        dir: src
        path: ci/docker/entrypoint.sh
        args:
          - bash
          - -ceux
          - |
            pushd ..
              docker load -i redis/image
              docker tag "$(cat redis/image-id)" "$(cat redis/repository):$(cat redis/tag)"
              docker load -i node/image
              docker tag "$(cat node/image-id)" "$(cat node/repository):$(cat node/tag)"
            popd
            docker-compose -f ci/docker/docker-compose.yml run app app/ci/tasks/test.sh
            docker-compose -f ci/docker/docker-compose.yml down
            docker volume rm $(docker volume ls -q)    


############################
#  JOBS

jobs:
      
  - name: test-and-deploy-((env))
    plan:
      - get: src
        resource: src-((branch))
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - do: *test
      - task: deploy
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            dir: src
            path: ci/tasks/deploy.sh
        params:
          <<: *cf
          CF_APP_NAME: pages-builder-((env))
          CF_MANIFEST: .cloudgov/manifest.yml
          CF_VARS_FILE: .cloudgov/vars/pages-((env)).yml
        on_failure:
          try:
            task: cancel-api-deployment
            config:
              <<: *cf-image
              inputs: [name: src]
              run:
                dir: src
                path: ci/tasks/cancel-deployment.sh
            params:
              <<: *cf
              CF_APP_NAME: pages-builder-((env))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages builder deployment on ((env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}      
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed pages builder on ((env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  # - name: test-and-deploy-production
  #   plan:
  #     - get: src
  #       resource: src-production
  #       trigger: true
  #       params: {depth: 1}
  #     - put: gh-status
  #       inputs: [src]
  #       params: {state: pending}
  #     - do: *test
  #     - task: deploy
  #       config:
  #         <<: *cf-image
  #         inputs: [name: src]
  #         run:
  #           dir: src
  #           path: ci/tasks/deploy.sh
  #       params:
  #         <<: *cf
  #         CF_APP_NAME: pages-builder-production
  #         CF_MANIFEST: .cloudgov/manifest.yml
  #         CF_VARS_FILE: .cloudgov/vars/pages-production.yml
  #       on_failure:
  #         try:
  #           task: cancel-api-deployment
  #           config:
  #             <<: *cf-image
  #             inputs: [name: src]
  #             run:
  #               dir: src
  #               path: ci/tasks/cancel-deployment.sh
  #           params:
  #             <<: *cf
  #             CF_APP_NAME: pages-builder-production
  #   on_failure:
  #     in_parallel:
  #       - put: gh-status
  #         inputs: [src]
  #         params: {state: failure}
  #       - put: slack
  #         params:
  #           text: |
  #             :x: FAILED: pages builder deployment on production
  #             <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  #           channel: ((slack-channel))
  #           username: ((slack-username))
  #           icon_url: ((slack-icon-url))
  #   on_success:
  #     in_parallel:
  #       - put: gh-status
  #         inputs: [src]
  #         params: {state: success}      
  #       - put: slack
  #         params:
  #           text: |
  #             :white_check_mark: SUCCESS: Successfully deployed pages builder on production
  #             <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  #           channel: ((slack-channel))
  #           username: ((slack-username))
  #           icon_url: ((slack-icon-url))

  - name: nightly-tasks-((env))
    plan:
      - get: src
        resource: src-((branch))
        params: {depth: 1}
      - get: nightly
        trigger: true
      - task: restage
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            path: src/ci/tasks/restage.sh
        params:
          <<: *cf
          CF_APP_NAME: pages-builder-((env))

  # - name: nightly-tasks-production
  #   plan:
  #     - get: src
  #       resource: src-production
  #       params: {depth: 1}
  #     - get: nightly
  #       trigger: true
  #     - task: restage
  #       config:
  #         <<: *cf-image
  #         inputs: [name: src]
  #         run:
  #           path: src/ci/tasks/restage.sh
  #       params:
  #         <<: *cf
  #         CF_APP_NAME: pages-builder-production

############################
#  RESOURCES

resources:

  - name: src-((env))
    type: git
    icon: github
    source:
      uri: https://github.com/18F/federalist-builder
      branch: ((branch))

  # - name: src-production
  #   type: git
  #   icon: github
  #   source:
  #     uri: https://github.com/18F/federalist-builder
  #     branch: main

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: 5-alpine

  - name: node
    type: docker-image
    source:
      repository: node
      tag: 16.14

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: 18F
      repo: federalist-builder
      access_token: ((gh-access-token))
      context_prefix: concourse

############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
